import type { TimesheetCardData } from "@/components/timesheet-card";
import type { TimesheetShiftCardData } from "@/components/timesheet-shift-card";

export const timesheetExamples: TimesheetCardData[] = [
  {
    initials: "GH",
    name: "House, Gregory MD",
    agency: "Princeton-Plainsboro Teaching Hospital • W2",
    dates: "Sep 1 – Sep 14, 2026",
    job: "Princeton-Plainsboro - Diagnostic Medicine #2214",
    facility: "Princeton-Plainsboro Teaching Hospital",
    shifts: 13,
    hours: 192,
    units: 0,
    expenses: 3,
    assignee: null,
    status: "Approved",
    actions: ["Details", "Reopen"],
  },
  {
    initials: "MG",
    name: "Grey, Meredith MD",
    agency: "Grey Sloan Memorial Hospital • W2",
    dates: "Aug 18 – Aug 31, 2026",
    job: "Grey Sloan Memorial - General Surgery #4401",
    facility: "Grey Sloan Memorial Hospital",
    shifts: 8,
    hours: 96,
    units: 0,
    expenses: 1,
    assignee: { name: "Morgan Ellis", initials: "ME" },
    status: "Pending Submission",
    actions: ["Details", "Submit"],
  },
  {
    initials: "PC",
    name: "Cox, Perry MD",
    agency: "Sacred Heart Hospital • W2",
    dates: "Jul 21 – Aug 3, 2026",
    job: "Sacred Heart - Internal Medicine #1102",
    facility: "Sacred Heart Hospital",
    shifts: 10,
    hours: 120,
    units: 2,
    expenses: 4,
    assignee: { name: "Priya Shah", initials: "PS" },
    status: "Disputed",
    actions: ["Details", "Resubmit"],
  },
  {
    initials: "SM",
    name: "Murphy, Shaun MD",
    agency: "St. Bonaventure Hospital • Locum",
    dates: "Sep 15 – Sep 28, 2026",
    job: "St. Bonaventure - General Surgery #5518",
    facility: "St. Bonaventure Hospital",
    shifts: 12,
    hours: 144,
    units: 0,
    expenses: 0,
    assignee: null,
    status: "Approved",
    actions: ["Details", "Reopen"],
  },
  {
    initials: "DR",
    name: "Ross, Doug MD",
    agency: "County General Hospital • Locum",
    dates: "Aug 4 – Aug 17, 2026",
    job: "County General - Pediatric Emergency #3306",
    facility: "County General Hospital",
    shifts: 6,
    hours: 72,
    units: 1,
    expenses: 2,
    assignee: { name: "Alex Kim", initials: "AK" },
    status: "Pending Approval",
    actions: ["Details", "Approve"],
  },
];

export const timesheetShiftExample: TimesheetShiftCardData = {
  title: "09/29: Hospitalist Night",
  scheduled: "09/29, 5:00 PM – 09/30, 5:00 AM PDT",
  activity: "Hospitalist Night",
  lines: [
    {
      label: "Base",
      time: "09/29, 7:00 PM – 09/30, 6:00 AM PDT",
      duration: "11 hrs 00 mins",
      rate: "$295.00 /hr",
      amount: "$3,540.00",
    },
    {
      label: "Overtime (Daily)",
      time: "09/30, 6:00 AM – 7:00 AM PDT",
      duration: "1 hr 00 mins",
      rate: "$442.50 /hr",
      amount: "$442.50",
      overtime: true,
    },
  ],
  total: "$3,982.50",
};
